MyFitnessApp/Web/MyFitnessApp.Web/Areas/Administration/Controllers/PostsController.cs
namespace MyFitnessApp.Web.Areas.Administration.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using MyFitnessApp.Data;
    using MyFitnessApp.Data.Models;

    public class PostsController : AdministrationController
    {
        private readonly ApplicationDbContext db;

        public PostsController(ApplicationDbContext context)
        {
            this.db = context;
        }

        // GET: Administration/Posts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = this.db.Posts.Include(p => p.AddedByUser).Include(p => p.Category);
            return this.View(await applicationDbContext.ToListAsync());
        }

        // GET: Administration/Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var post = await this.db.Posts
                .Include(p => p.AddedByUser)
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return this.NotFound();
            }

            return this.View(post);
        }

        // GET: Administration/Posts/Create
        public IActionResult Create()
        {
            this.ViewData["AddedByUserId"] = new SelectList(this.db.Users, "Id", "Id");
            this.ViewData["CategoryId"] = new SelectList(this.db.ForumCategories, "Id", "Description");
            return this.View();
        }

        // POST: Administration/Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Content,AddedByUserId,CategoryId,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Post post)
        {
            if (this.ModelState.IsValid)
            {
                this.db.Add(post);
                await this.db.SaveChangesAsync();
                return this.RedirectToAction(nameof(this.Index));
            }

            this.ViewData["AddedByUserId"] = new SelectList(this.db.Users, "Id", "Id", post.AddedByUserId);
            this.ViewData["CategoryId"] = new SelectList(this.db.ForumCategories, "Id", "Description", post.CategoryId);
            return this.View(post);
        }

        // GET: Administration/Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var post = await this.db.Posts.FindAsync(id);
            if (post == null)
            {
                return this.NotFound();
            }

            this.ViewData["AddedByUserId"] = new SelectList(this.db.Users, "Id", "Id", post.AddedByUserId);
            this.ViewData["CategoryId"] = new SelectList(this.db.ForumCategories, "Id", "Description", post.CategoryId);
            return this.View(post);
        }

        // POST: Administration/Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Title,Content,AddedByUserId,CategoryId,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Post post)
        {
            if (id != post.Id)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    this.db.Update(post);
                    await this.db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.PostExists(post.Id))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }

            this.ViewData["AddedByUserId"] = new SelectList(this.db.Users, "Id", "Id", post.AddedByUserId);
            this.ViewData["CategoryId"] = new SelectList(this.db.ForumCategories, "Id", "Description", post.CategoryId);
            return this.View(post);
        }

        // GET: Administration/Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var post = await this.db.Posts
                .Include(p => p.AddedByUser)
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return this.NotFound();
            }

            return this.View(post);
        }

        // POST: Administration/Posts/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await this.db.Posts.FindAsync(id);
            this.db.Posts.Remove(post);
            await this.db.SaveChangesAsync();
            return this.RedirectToAction(nameof(this.Index));
        }

        private bool PostExists(int id)
        {
            return this.db.Posts.Any(e => e.Id == id);
        }
    }
}

MyFitnessApp/Web/MyFitnessApp.Web/Controllers/CommentsController.cs
namespace MyFitnessApp.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyFitnessApp.Services.Data.Comment;
    using MyFitnessApp.Web.Filters;
    using MyFitnessApp.Web.ViewModels.Comments;

    [Authorize]
    [TypeFilter(typeof(RestrictBannedUsersAttribute))]
    [TypeFilter(typeof(RestrictUsersWithoutProfileAttribute))]
    public class CommentsController : Controller
    {
        private readonly ICommentsService commentsService;

        public CommentsController(ICommentsService commentsService)
        {
            this.commentsService = commentsService;
        }

        [HttpGet]
        public IActionResult Reply()
        {
            var viewModel = new CreateCommentInputModel();
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Reply(int id, CreateCommentInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var userId = this.User.GetId();
            await this.commentsService.CreateCommentAsync(model, userId, id);

            return this.RedirectToAction("ById", "Posts", new { id = id });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int commentId, int postId)
        {
            await this.commentsService.DeleteCommentAsync(commentId);
            return this.RedirectToAction("ById", "Posts", new { id = postId });
        }
    }
}

MyFitnessApp/Web/MyFitnessApp.Web/Controllers/ForumsController.cs
namespace MyFitnessApp.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyFitnessApp.Services.Data.Forum;
    using MyFitnessApp.Web.Filters;
    using MyFitnessApp.Web.ViewModels.Forum;

    [Authorize]
    [TypeFilter(typeof(RestrictBannedUsersAttribute))]
    [TypeFilter(typeof(RestrictUsersWithoutProfileAttribute))]
    public class ForumsController : Controller
    {
        private readonly IForumsService forumsService;

        public ForumsController(IForumsService forumsService)
        {
            this.forumsService = forumsService;
        }

        [HttpGet]
        public IActionResult Categories()
        {
            var categories = this.forumsService.GetAllCategories();
            var viewModel = new AllCategoriesViewModel
            {
                Categories = categories,
            };

            return this.View(viewModel);
        }

        [HttpGet]
        public IActionResult ByName(string name)
        {
            var viewModel = this.forumsService.GetCategoryByName(name);

            return this.View(viewModel);
        }
    }
}

MyFitnessApp/Web/MyFitnessApp.Web/Controllers/PostsController.cs
namespace MyFitnessApp.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyFitnessApp.Services.Data.Forum;
    using MyFitnessApp.Services.Data.Post;
    using MyFitnessApp.Web.Filters;
    using MyFitnessApp.Web.ViewModels.Posts;

    [Authorize]
    [TypeFilter(typeof(RestrictBannedUsersAttribute))]
    [TypeFilter(typeof(RestrictUsersWithoutProfileAttribute))]
    public class PostsController : Controller
    {
        private readonly IPostsService postsService;

        public PostsController(IPostsService postsService)
        {
            this.postsService = postsService;
        }

        [HttpGet]
        public IActionResult Create()
        {
            var viewModel = new CreatePostInputModel
            {
                Categories = this.postsService.GetForumCategories(),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePostInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                model.Categories = this.postsService.GetForumCategories();
                return this.View(model);
            }

            var userId = this.User.GetId();
            var postId = await this.postsService.CreatePostAsync(model, userId);

            this.TempData["Message"] = "Post created successfully.";

            return this.RedirectToAction("ById", new { id = postId });
        }

        [HttpGet]
        public IActionResult ById(int id)
        {
            var postViewModel = this.postsService.GetPostById(id);

            if (postViewModel == null)
            {
                return this.NotFound();
            }

            return this.View(postViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await this.postsService.DeletePostAsync(id);
            return this.RedirectToAction("Categories", "Forums");
        }
    }
}

MyFitnessApp/Web/MyFitnessApp.Web/Views/Posts/ById.cshtml
@model PostViewModel

@{
    this.ViewData["Title"] = $"Post by {Model.AddedByUserUserName}";
    var userId = User.GetId();
}

<!-- Breadcrumb -->
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Forums/Categories">Forum</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@this.ViewData["Title"]</strong></li>
    </ol>
</nav>
<!-- /Breadcrumb -->

@if (this.TempData.ContainsKey("Message"))
{
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <strong>@this.TempData["Message"]</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="container-fluid mt-100">
    <div class="row">
        <div class="col">
            <div class="card mb-4 border-dark">
                <div class="card-header">
                    <div class="media flex-wrap w-100 align-items-center">
                        <img src="@Model.UserProfileImage" class="rounded-circle" width="70" alt="">
                        <div class="media-body ml-3">
                            <div>
                                <h4>@Model.Title</h4>
                            </div>
                            <div class="text-muted small">
                                <strong>Post by:</strong>
                                <a asp-area="" asp-controller="Profiles" asp-action="UsersProfile" asp-route-username="@Model.AddedByUserUserName">@Model.AddedByUserUserName</a>
                            </div>
                            <div class="text-muted small">
                                <strong>Category:</strong>
                                <a href="/Forums/ByName/@Model.CategoryName">
                                    @Model.CategoryName
                                </a>
                            </div>
                            <div class="text-muted small">
                                <strong>Created on:</strong> @Model.CreatedOn.ToString("f")
                            </div>
                            <div class="text-muted small">
                                <strong>Member since:</strong> @Model.AddedByUserCreatedOn.ToString("dddd, dd MMMM yyyy")
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <article>
                        @Model.Content
                    </article>
                </div>
                @if (userId == Model.AddedByUserId || User.IsInRole("Administrator"))
                {
                    <div class="text-center">
                        <form method="post" asp-controller="Posts" asp-action="Delete" id="deleteForm" asp-route-id="@Model.Id"></form>
                        <button class="btn btn-outline-danger mt-3" data-toggle="modal" data-target="#deleteModal">Delete post</button>
                    </div>
                }

                @foreach (var reply in Model.Comments)
                {
                    <div class="container mt-2">
                        <div class="col-xl-11 offset-xl-1 col-lg-11 offset-lg-1 col-md-11 offset-md-1 col-xs-11 offset-xs-1 col-11 offset-1">
                            <div class="card border-dark mt-2">
                                <div class="card-header">
                                    <div class="media flex-wrap w-100 align-items-center">
                                        <img src="@reply.UserProfileImage" class="rounded-circle" width="70" alt="">
                                        <div class="media-body ml-3">
                                            <div class="text-muted small">
                                                <strong>Comment by:</strong>
                                                <a asp-area="" asp-controller="Profiles" asp-action="UsersProfile" asp-route-username="@reply.AddedByUserUserName">@reply.AddedByUserUserName</a>
                                            </div>
                                            <div class="text-muted small">
                                                <strong>Created on:</strong> @reply.CreatedOn.ToString("f")
                                            </div>
                                            <div class="text-muted small">
                                                <strong>Member since:</strong> @reply.AddedByUserCreatedOn.ToString("dddd, dd MMMM yyyy")
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <article>
                                        @reply.Content
                                    </article>
                                </div>


                                @if (userId == reply.AddedByUserId || User.IsInRole("Administrator"))
                                {
                                    <div class="text-right m-2">
                                        <form method="post" asp-controller="Comments" asp-action="Delete" asp-route-commentId="@reply.Id" asp-route-postId="@Model.Id">
                                            <button class="btn btn-outline-danger mt-3">Delete comment</button>
                                        </form>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                }
                <div class="card-footer mt-2">
                    <div class="text-center">
                        <a asp-controller="Comments" asp-action="Reply" asp-route-id="@Model.Id" class="btn btn-outline-secondary m-1">Reply</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="text-center">
    <a asp-controller="Forums" asp-action="Categories" class="btn btn-outline-secondary m-1">Back to forum categories</a>
</div>

<div class="modal" tabindex="-1" role="dialog" id="deleteModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <p>Are you sure you want to remove "@Model.Title"?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" onclick="deleteForm.submit()">Yes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
            </div>
        </div>
    </div>
</div>

MyFitnessApp/Web/MyFitnessApp.Web/Views/Posts/Create.cshtml
@model MyFitnessApp.Web.ViewModels.Posts.CreatePostInputModel

@{
    this.ViewData["Title"] = "Create forum post";
}

<!-- Breadcrumb -->
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Forums/Categories">Forums</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@this.ViewData["Title"]</strong></li>
    </ol>
</nav>
<!-- /Breadcrumb -->

<div class="container">
    <div class="row">
        <div class="offset-lg-2 col-lg-8 col-sm-12 offset-xl-3 col-xl-6">
            <form method="post">
                <div class="form-group">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control" placeholder="Title here...">
                    <span asp-validation-for="Title" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Content"></label>
                    <textarea asp-for="Content" class="form-control" rows="14" placeholder="Content here..."></textarea>
                    <span asp-validation-for="Content" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CategoryId"></label>
                    <select asp-for="CategoryId" class="form-control">
                        @foreach (var category in Model.Categories)
                        {
                            <option value="@category.Id">@category.Name</option>
                        }
                    </select>
                </div>

                <div class="text-center pt-2">
                    <input class="btn btn-outline-secondary" type="submit" value="Save" />
                </div>
            </form>
        </div>
    </div>
</div>