MyFitnessApp/Web/MyFitnessApp.Web/Areas/Administration/Controllers/DashboardController.cs
namespace MyFitnessApp.Web.Areas.Administration.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using MyFitnessApp.Services.Data.Article;
    using MyFitnessApp.Services.Data.Exercise;
    using MyFitnessApp.Services.Data.Food;
    using MyFitnessApp.Services.Data.Post;
    using MyFitnessApp.Services.Data.User;
    using MyFitnessApp.Web.ViewModels.Administration.Dashboard;

    public class DashboardController : AdministrationController
    {
        private readonly IUsersService usersService;
        private readonly IArticlesService articlesService;
        private readonly IExercisesService exercisesService;
        private readonly IPostsService postService;
        private readonly IFoodsService foodsService;

        public DashboardController(
            IUsersService usersService,
            IArticlesService articlesService,
            IExercisesService exercisesService,
            IPostsService postService,
            IFoodsService foodsService)
        {
            this.usersService = usersService;
            this.articlesService = articlesService;
            this.exercisesService = exercisesService;
            this.postService = postService;
            this.foodsService = foodsService;
        }

        public IActionResult Index()
        {
            var viewModel = new IndexViewModel()
            {
                UsersCount = this.usersService.GetCounts(),
                ArticlesCount = this.articlesService.GetCounts(),
                FoodsCount = this.foodsService.GetCounts(),
                PostsCount = this.postService.GetCounts(),
                ExercisesCount = this.exercisesService.GetCounts(),
            };

            return this.View(viewModel);
        }
    }
}

MyFitnessApp/Web/MyFitnessApp.Web/Controllers/PostsController.cs
namespace MyFitnessApp.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyFitnessApp.Services.Data.Forum;
    using MyFitnessApp.Services.Data.Post;
    using MyFitnessApp.Web.Filters;
    using MyFitnessApp.Web.ViewModels.Posts;

    [Authorize]
    [TypeFilter(typeof(RestrictBannedUsersAttribute))]
    [TypeFilter(typeof(RestrictUsersWithoutProfileAttribute))]
    public class PostsController : Controller
    {
        private readonly IPostsService postsService;

        public PostsController(IPostsService postsService)
        {
            this.postsService = postsService;
        }

        [HttpGet]
        public IActionResult Create()
        {
            var viewModel = new CreatePostInputModel
            {
                Categories = this.postsService.GetForumCategories(),
            };

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreatePostInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                model.Categories = this.postsService.GetForumCategories();
                return this.View(model);
            }

            var userId = this.User.GetId();
            var postId = await this.postsService.CreatePostAsync(model, userId);

            this.TempData["Message"] = "Post created successfully.";

            return this.RedirectToAction("ById", new { id = postId });
        }

        [HttpGet]
        public IActionResult ById(int id)
        {
            var postViewModel = this.postsService.GetPostById(id);

            if (postViewModel == null)
            {
                return this.NotFound();
            }

            return this.View(postViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await this.postsService.DeletePostAsync(id);
            return this.RedirectToAction("Categories", "Forums");
        }
    }
}

MyFitnessApp/Web/MyFitnessApp.Web/Controllers/UsersController.cs
namespace MyFitnessApp.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Mvc;
    using MyFitnessApp.Services.Data.Profile;
    using MyFitnessApp.Services.Data.User;
    using MyFitnessApp.Web.Filters;
    using MyFitnessApp.Web.ViewModels.Users;

    [Authorize]
    [TypeFilter(typeof(RestrictBannedUsersAttribute))]
    [TypeFilter(typeof(RestrictUsersWithoutProfileAttribute))]
    public class UsersController : Controller
    {
        private readonly IUsersService usersService;
        private readonly IProfilesService profilesService;

        public UsersController(
            IUsersService usersService,
            IProfilesService profilesService)
        {
            this.usersService = usersService;
            this.profilesService = profilesService;
        }

        [HttpPost]
        public async Task<IActionResult> Follow(string username)
        {
            var loggedUserId = this.User.GetId();
            var searchedUserId = this.profilesService.GetUserIdByUserName(username);
            await this.usersService.Follow(loggedUserId, searchedUserId);

            this.TempData["Message"] = $"Successfully followed {username}";
            return this.Redirect($"/Profiles/UsersProfile?username={username}");
        }

        [HttpPost]
        public async Task<IActionResult> Unfollow(string username)
        {
            var loggedUserId = this.User.GetId();
            var searchedUserId = this.profilesService.GetUserIdByUserName(username);
            await this.usersService.Unfollow(loggedUserId, searchedUserId);

            this.TempData["Message"] = @$"Successfully unfollowed {username}";
            return this.Redirect($"/Profiles/UsersProfile?username={username}");
        }

        [HttpGet]
        public IActionResult Followers()
        {
            var userId = this.User.GetId();
            var followers = this.usersService.GetFollowers(userId);
            var viewModel = new AllFollowerFolloweeViewModel()
            {
                FollowerFollowees = followers,
            };

            return this.View(viewModel);
        }

        [HttpGet]
        public IActionResult Followees()
        {
            var userId = this.User.GetId();
            var followees = this.usersService.GetFollowees(userId);
            var viewModel = new AllFollowerFolloweeViewModel()
            {
                FollowerFollowees = followees,
            };

            return this.View(viewModel);
        }

        [HttpGet]
        public IActionResult All()
        {
            var users = this.usersService.All();
            var viewModel = new AllUsersViewModel()
            {
                Users = users,
            };

            return this.View(viewModel);
        }
    }
}

MyFitnessApp/Web/MyFitnessApp.Web/Areas/Administration/Views/Dashboard/Index.cshtml
@model MyFitnessApp.Web.ViewModels.Administration.Dashboard.IndexViewModel
@{
    this.ViewData["Title"] = "Admin dashboard";
}

<!-- Breadcrumb -->
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@this.ViewData["Title"]</strong></li>
    </ol>
</nav>
<!-- /Breadcrumb -->

<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12 mb-4">
            <div class="counter-box">
                <a asp-controller="Users" asp-action="All">
                    <i class="fa fa-user"></i>
                    <span class="counter">@Model.UsersCount</span>
                    <p>Total users</p>
                </a>
            </div>
        </div>
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12 mb-4">
            <div class="counter-box">
                <a asp-controller="Exercises" asp-action="Index">
                    <i class="fa fa-running"></i>
                    <span class="counter">@Model.ExercisesCount</span>
                    <p>Total exercises</p>
                </a>
            </div>
        </div>
        <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12 mb-4">
            <div class="counter-box">
                <a asp-controller="Articles" asp-action="Index">
                    <i class="fa fa-newspaper"></i>
                    <span class="counter">@Model.ArticlesCount</span>
                    <p>Total articles</p>
                </a>
            </div>
        </div>
    </div>
</div>

<div class="row d-flex justify-content-center">
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12 mb-4">
        <div class="counter-box">
            <a asp-controller="Posts" asp-action="Index">
                <i class="fa fa-edit"></i>
                <span class="counter">@Model.PostsCount</span>
                <p>Total posts</p>
            </a>
        </div>
    </div>
    <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12 col-12 mb-4">
        <div class="counter-box">
            <a asp-controller="Foods" asp-action="Index">
                <i class="fa fa-drumstick-bite"></i>
                <span class="counter">@Model.FoodsCount</span>
                <p>Total foods</p>
            </a>
        </div>
    </div>
</div>