MyFitnessApp/Web/MyFitnessApp.Web/Areas/Administration/Controllers/ExercisesController.cs
namespace MyFitnessApp.Web.Areas.Administration.Controllers
{
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.EntityFrameworkCore;
    using MyFitnessApp.Data;
    using MyFitnessApp.Data.Models;

    public class ExercisesController : AdministrationController
    {
        private readonly ApplicationDbContext db;

        public ExercisesController(ApplicationDbContext context)
        {
            this.db = context;
        }

        // GET: Administration/Exercises
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = this.db.Exercises.Include(e => e.AddedByUser).Include(e => e.Category).Include(e => e.Equipment);
            return this.View(await applicationDbContext.ToListAsync());
        }

        // GET: Administration/Exercises/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var exercise = await this.db.Exercises
                .Include(e => e.AddedByUser)
                .Include(e => e.Category)
                .Include(e => e.Equipment)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (exercise == null)
            {
                return this.NotFound();
            }

            return this.View(exercise);
        }

        // GET: Administration/Exercises/Create
        public IActionResult Create()
        {
            this.ViewData["AddedByUserId"] = new SelectList(this.db.Users, "Id", "Id");
            this.ViewData["CategoryId"] = new SelectList(this.db.ExerciseCategories, "Id", "Name");
            this.ViewData["EquipmentId"] = new SelectList(this.db.ExerciseEquipments, "Id", "Name");
            return this.View();
        }

        // POST: Administration/Exercises/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,Difficulty,CategoryId,EquipmentId,ImageUrl,VideoUrl,AddedByUserId,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Exercise exercise)
        {
            if (this.ModelState.IsValid)
            {
                this.db.Add(exercise);
                await this.db.SaveChangesAsync();
                return this.RedirectToAction(nameof(this.Index));
            }

            this.ViewData["AddedByUserId"] = new SelectList(this.db.Users, "Id", "Id", exercise.AddedByUserId);
            this.ViewData["CategoryId"] = new SelectList(this.db.ExerciseCategories, "Id", "Name", exercise.CategoryId);
            this.ViewData["EquipmentId"] = new SelectList(this.db.ExerciseEquipments, "Id", "Name", exercise.EquipmentId);
            return this.View(exercise);
        }

        // GET: Administration/Exercises/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var exercise = await this.db.Exercises.FindAsync(id);
            if (exercise == null)
            {
                return this.NotFound();
            }

            this.ViewData["AddedByUserId"] = new SelectList(this.db.Users, "Id", "Id", exercise.AddedByUserId);
            this.ViewData["CategoryId"] = new SelectList(this.db.ExerciseCategories, "Id", "Name", exercise.CategoryId);
            this.ViewData["EquipmentId"] = new SelectList(this.db.ExerciseEquipments, "Id", "Name", exercise.EquipmentId);
            return this.View(exercise);
        }

        // POST: Administration/Exercises/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Description,Difficulty,CategoryId,EquipmentId,ImageUrl,VideoUrl,AddedByUserId,IsDeleted,DeletedOn,Id,CreatedOn,ModifiedOn")] Exercise exercise)
        {
            if (id != exercise.Id)
            {
                return this.NotFound();
            }

            if (this.ModelState.IsValid)
            {
                try
                {
                    this.db.Update(exercise);
                    await this.db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!this.ExerciseExists(exercise.Id))
                    {
                        return this.NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return this.RedirectToAction(nameof(this.Index));
            }

            this.ViewData["AddedByUserId"] = new SelectList(this.db.Users, "Id", "Id", exercise.AddedByUserId);
            this.ViewData["CategoryId"] = new SelectList(this.db.ExerciseCategories, "Id", "Name", exercise.CategoryId);
            this.ViewData["EquipmentId"] = new SelectList(this.db.ExerciseEquipments, "Id", "Name", exercise.EquipmentId);
            return this.View(exercise);
        }

        // GET: Administration/Exercises/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return this.NotFound();
            }

            var exercise = await this.db.Exercises
                .Include(e => e.AddedByUser)
                .Include(e => e.Category)
                .Include(e => e.Equipment)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (exercise == null)
            {
                return this.NotFound();
            }

            return this.View(exercise);
        }

        // POST: Administration/Exercises/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var exercise = await this.db.Exercises.FindAsync(id);
            this.db.Exercises.Remove(exercise);
            await this.db.SaveChangesAsync();
            return this.RedirectToAction(nameof(this.Index));
        }

        private bool ExerciseExists(int id)
        {
            return this.db.Exercises.Any(e => e.Id == id);
        }
    }
}

MyFitnessApp/Web/MyFitnessApp.Web/Controllers/ExerciseCategoriesController.cs
namespace MyFitnessApp.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyFitnessApp.Services.Data.Exercise;
    using MyFitnessApp.Web.Filters;
    using MyFitnessApp.Web.ViewModels.Exercises;

    [Authorize]
    [TypeFilter(typeof(RestrictBannedUsersAttribute))]
    [TypeFilter(typeof(RestrictUsersWithoutProfileAttribute))]
    public class ExerciseCategoriesController : Controller
    {
        private readonly IExercisesService exercisesService;

        public ExerciseCategoriesController(IExercisesService exercisesService)
        {
            this.exercisesService = exercisesService;
        }

        [HttpGet]
        public IActionResult Shoulders()
        {
            var view = new AllExercisesViewModel
            {
                Exercises = this.exercisesService.GetExercisesByCategoryId(1),
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Triceps()
        {
            var view = new AllExercisesViewModel
            {
                Exercises = this.exercisesService.GetExercisesByCategoryId(2),
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Biceps()
        {
            var view = new AllExercisesViewModel
            {
                Exercises = this.exercisesService.GetExercisesByCategoryId(3),
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Back()
        {
            var view = new AllExercisesViewModel
            {
                Exercises = this.exercisesService.GetExercisesByCategoryId(4),
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Chest()
        {
            var view = new AllExercisesViewModel
            {
                Exercises = this.exercisesService.GetExercisesByCategoryId(5),
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Forearm()
        {
            var view = new AllExercisesViewModel
            {
                Exercises = this.exercisesService.GetExercisesByCategoryId(6),
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Traps()
        {
            var view = new AllExercisesViewModel
            {
                Exercises = this.exercisesService.GetExercisesByCategoryId(7),
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Abs()
        {
            var view = new AllExercisesViewModel
            {
                Exercises = this.exercisesService.GetExercisesByCategoryId(8),
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Glutes()
        {
            var view = new AllExercisesViewModel
            {
                Exercises = this.exercisesService.GetExercisesByCategoryId(9),
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Quadriceps()
        {
            var view = new AllExercisesViewModel
            {
                Exercises = this.exercisesService.GetExercisesByCategoryId(10),
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Hamstrings()
        {
            var view = new AllExercisesViewModel
            {
                Exercises = this.exercisesService.GetExercisesByCategoryId(11),
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Calves()
        {
            var view = new AllExercisesViewModel
            {
                Exercises = this.exercisesService.GetExercisesByCategoryId(12),
            };

            return this.View(view);
        }
    }
}

MyFitnessApp/Web/MyFitnessApp.Web/Controllers/ExercisesController.cs
namespace MyFitnessApp.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyFitnessApp.Services.Data.Exercise;
    using MyFitnessApp.Web.Filters;
    using MyFitnessApp.Web.ViewModels.Exercises;

    [Authorize]
    [TypeFilter(typeof(RestrictBannedUsersAttribute))]
    [TypeFilter(typeof(RestrictUsersWithoutProfileAttribute))]
    public class ExercisesController : Controller
    {
        private readonly IExercisesService exercisesService;

        public ExercisesController(IExercisesService exercisesService)
        {
            this.exercisesService = exercisesService;
        }

        [HttpGet]
        public IActionResult Create()
        {
            var viewModel = new CreateExerciseInputModel();
            viewModel.Categories = this.exercisesService.GetExerciseCategories();
            viewModel.Equipments = this.exercisesService.GetExerciseEquipments();

            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateExerciseInputModel model)
        {
            if (!this.ModelState.IsValid)
            {
                model.Categories = this.exercisesService.GetExerciseCategories();
                model.Equipments = this.exercisesService.GetExerciseEquipments();

                return this.View(model);
            }

            var userId = this.User.GetId();
            await this.exercisesService.CreateExcerciseAsync(model, userId);

            this.TempData["Message"] = "Exercise created successfully.";

            return this.RedirectToAction("All", "Exercises");
        }

        [HttpGet]
        public IActionResult All(int id = 1)
        {
            const int itemsPerPage = 6;
            var view = new AllExercisesViewModel
            {
                PageNumber = id,
                Exercises = this.exercisesService.GetAllExercises(id, itemsPerPage),
                ItemsCount = this.exercisesService.GetCounts(),
                ItemsPerPage = itemsPerPage,
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Add(int id)
        {
            var viewNodel = this.exercisesService.GetExerciseById(id);
            return this.View(viewNodel);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddExerciseInputModel model, int id)
        {
            if (!this.ModelState.IsValid)
            {
                var viewNodel = this.exercisesService.GetExerciseById(id);
                return this.View(viewNodel);
            }

            var userId = this.User.GetId();
            await this.exercisesService.AddExerciseToUserAsync(model, userId);
            var dayOfWeek = model.WeekDay.ToString();

            this.TempData["Message"] = "Exercise added to my diary.";

            return this.RedirectToAction(dayOfWeek, "ExerciseDiary");
        }

        [HttpGet]
        public IActionResult Categories()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Remove(int id, string day)
        {
            var userId = this.User.GetId();
            await this.exercisesService.RemoveExerciseAsync(userId, id);
            return this.Redirect($"/ExerciseDiary/{day}");
        }
    }
}

MyFitnessApp/Web/MyFitnessApp.Web/Views/Exercises/Add.cshtml
@model AddExerciseInputModel

@{
   this.ViewData["Title"] = Model.Name;
}

<!-- Breadcrumb -->
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Exercises/All">All exercises</a></li>
        <li class="breadcrumb-item"><a href="/ExerciseCategories/@Model.CategoryName">@Model.CategoryName</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@this.ViewData["Title"]</strong></li>
    </ol>
</nav>
<!-- /Breadcrumb -->

<div class="container">
    <div class="row">
        <div class="col-lg-3 col-xl-3">
            <partial name="_AddPartial" model="@Model" />
        </div>

        <div class="col-lg-9 col-xl-9 mt-3">
            <div class="row">
                <div class="col-md-6">
                    <p class="img" ">
                        <img src="@Model.ImageUrl" class="img-fluid" alt="Responsive image" />
                    </p>
                </div>
                <div class="col-md-6">
                    <p class="item-description">
                        <strong>Muscle group: </strong>@Model.CategoryName
                    </p>
                    <p class="item-description">
                        <strong>Equipment: </strong>@Model.EquipmentName
                    </p>
                    <p class="item-description">
                        <strong>Difficulty: </strong>@Model.DifficultyName
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="@Model.VideoUrl" allowfullscreen></iframe>
                    </div>
                </div>
                <div class="col-md-6">
                    <p class="item-description">
                        <strong>Instructions: </strong>@Model.Description
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

MyFitnessApp/Web/MyFitnessApp.Web/Views/Exercises/All.cshtml
@model AllExercisesViewModel

@{
    this.ViewData["Title"] = "All exercises";
}

<!-- Breadcrumb -->
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Exercises/Categories">Exercise by muscle group</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@this.ViewData["Title"]</strong></li>
    </ol>
</nav>
<!-- /Breadcrumb -->

@if (this.TempData.ContainsKey("Message"))
{
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <strong>@this.TempData["Message"]</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="container-fluid">
    <div class="row">
        @foreach (var exercise in Model.Exercises)
        {
            <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12 p-1">
                <a asp-controller="Exercises" asp-action="Add" asp-route-id="@exercise.Id">
                    <div class="card border-dark">
                        <div class="card card-body text-center alert-secondary">
                            <div class="text">
                                <h6><strong> @exercise.Name</strong></h6>
                            </div>
                            <div class="media flex-wrap w-100 align-items-center mt-2">
                                <img src="@exercise.ImageUrl" width="220" class="card-img-top">
                            </div>
                            <div class="text-muted mt-2">
                                Category: @exercise.CategoryName
                            </div>
                            <div class="text-muted">
                                Difficulty: @exercise.Difficulty
                            </div>
                            <div class="text-muted">
                                Equipment: @exercise.EquipmentName
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        }
    </div>
</div>

<hr />

<partial name="_ExercisesPagingPartial" model="@Model" />

MyFitnessApp/Web/MyFitnessApp.Web/Views/Exercises/Categories.cshtml
@{
    this.ViewData["Title"] = "Muscle groups";
}

<!-- Breadcrumb -->
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Exercises/All">All exercises</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@ViewData["Title"]</strong></li>
    </ol>
</nav>
<!-- /Breadcrumb -->

<div>
    <div class="row text-center">
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-6 p-1">
            <a asp-controller="ExerciseCategories" asp-action="Shoulders">
                <div class="card border-dark">
                    <div class="card-header col-md border text-center">
                        <div class="media flex-wrap w-100 align-items-center">
                            <img src="/images/exercisecategories/shoulders.jpg" class="card-img-top">
                        </div>
                        <div class="card card-body text-center alert-secondary">
                            <h5>Shoulders</h5>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-6 p-1">
            <a asp-controller="ExerciseCategories" asp-action="Triceps">
                <div class="card border-dark">
                    <div class="card-header col-md border text-center">
                        <div class="media flex-wrap w-100 align-items-center">
                            <img src="/images/exercisecategories/triceps.jpg" class="card-img-top">
                        </div>
                        <div class="card card-body text-center alert-secondary">
                            <h5>Triceps</h5>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-6 p-1">
            <a asp-controller="ExerciseCategories" asp-action="Biceps">
                <div class="card border-dark">
                    <div class="card-header col-md border text-center">
                        <div class="media flex-wrap w-100 align-items-center">
                            <img src="/images/exercisecategories/biceps.jpg" class="card-img-top">
                        </div>
                        <div class="card card-body text-center alert-secondary">
                            <h5>Biceps</h5>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-6 p-1">
            <a asp-controller="ExerciseCategories" asp-action="Back">
                <div class="card border-dark">
                    <div class="card-header col-md border text-center">
                        <div class="media flex-wrap w-100 align-items-center">
                            <img src="/images/exercisecategories/back.jpg" class="card-img-top">
                        </div>
                        <div class="card card-body text-center alert-secondary">
                            <h5>Back</h5>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-6 p-1">
            <a asp-controller="ExerciseCategories" asp-action="Chest">
                <div class="card border-dark">
                    <div class="card-header col-md border text-center">
                        <div class="media flex-wrap w-100 align-items-center">
                            <img src="/images/exercisecategories/chest.jpg" class="card-img-top">
                        </div>
                        <div class="card card-body text-center alert-secondary">
                            <h5>Chest</h5>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-6 p-1">
            <a asp-controller="ExerciseCategories" asp-action="Forearm">
                <div class="card border-dark">
                    <div class="card-header col-md border text-center">
                        <div class="media flex-wrap w-100 align-items-center">
                            <img src="/images/exercisecategories/forearms.jpg" class="card-img-top">
                        </div>
                        <div class="card card-body text-center alert-secondary">
                            <h5>Forearm</h5>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-6 p-1">
            <a asp-controller="ExerciseCategories" asp-action="Traps">
                <div class="card border-dark">
                    <div class="card-header col-md border text-center">
                        <div class="media flex-wrap w-100 align-items-center">
                            <img src="/images/exercisecategories/traps.jpg" class="card-img-top">
                        </div>
                        <div class="card card-body text-center alert-secondary">
                            <h5>Traps</h5>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-6 p-1">
            <a asp-controller="ExerciseCategories" asp-action="Abs">
                <div class="card border-dark">
                    <div class="card-header col-md border text-center">
                        <div class="media flex-wrap w-100 align-items-center">
                            <img src="/images/exercisecategories/abs.jpg" class="card-img-top">
                        </div>
                        <div class="card card-body text-center alert-secondary">
                            <h5>Abs</h5>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-6 p-1">
            <a asp-controller="ExerciseCategories" asp-action="Glutes">
                <div class="card border-dark">
                    <div class="card-header col-md border text-center">
                        <div class="media flex-wrap w-100 align-items-center">
                            <img src="/images/exercisecategories/glutes.jpg" class="card-img-top">
                        </div>
                        <div class="card card-body text-center alert-secondary">
                            <h5>Glutes</h5>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-6 p-1">
            <a asp-controller="ExerciseCategories" asp-action="Quadriceps">
                <div class="card border-dark">
                    <div class="card-header col-md border text-center">
                        <div class="media flex-wrap w-100 align-items-center">
                            <img src="/images/exercisecategories/quads.jpg" class="card-img-top">
                        </div>
                        <div class="card card-body text-center alert-secondary">
                            <h5>Quadriceps</h5>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-6 p-1">
            <a asp-controller="ExerciseCategories" asp-action="Hamstrings">
                <div class="card border-dark">
                    <div class="card-header col-md border text-center">
                        <div class="media flex-wrap w-100 align-items-center">
                            <img src="/images/exercisecategories/hamstrings.jpg" class="card-img-top">
                        </div>
                        <div class="card card-body text-center alert-secondary">
                            <h5>Hamstrings</h5>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-6 p-1">
            <a asp-controller="ExerciseCategories" asp-action="Calves">
                <div class="card border-dark">
                    <div class="card-header col-md border text-center">
                        <div class="media flex-wrap w-100 align-items-center">
                            <img src="/images/exercisecategories/calves.jpg" class="card-img-top">
                        </div>
                        <div class="card card-body text-center alert-secondary">
                            <h5>Calves</h5>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

MyFitnessApp/Web/MyFitnessApp.Web/Views/Exercises/MyExercises.cshtml
@model AllExercisesViewModel

@{
    var userName = this.User.Identity.Name;
    this.ViewData["Title"] = "Exercises created by" + " " + userName;
}

<!-- Breadcrumb -->
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Exercises/All">All exercises</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@ViewData["Title"]</strong></li>
    </ol>
</nav>
<!-- /Breadcrumb -->

<div>
    <div class="row">
        @foreach (var exercise in Model.Exercises)
        {
            <div class="col-md-4 mt-3">
                <div class="card text-center alert-info" style="width: 18rem;">
                    <a asp-action="Add" asp-route-id="@exercise.Id">
                        <img src="@exercise.ImageUrl" class="card-img-top">
                    </a>
                    <div class="card-body">
                        <h5 class="card-title"> <a asp-action="Add" asp-route-id="@exercise.Id">@exercise.Name</a></h5>
                        Target Muscle Group:
                        <a asp-controller="ExerciseCategories" asp-action="@exercise.CategoryName">
                            <p class="card-text"> @exercise.CategoryName</p>
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

MyFitnessApp/Web/MyFitnessApp.Web/Views/Exercises/_AddPartial.cshtml
@using MyFitnessApp.Data.Models

@model AddExerciseInputModel

<div class="container">
    <div class="row">
        <div class="col-lg-12 col-xl-12 col-md-10 offset-1 col-sm-10 offset-1">
            <form method="post">
                    <div class="form-group">
                        <label asp-for="Weight"></label>
                        <input asp-for="Weight" class="form-control" placeholder="enter weight here...">
                        <span asp-validation-for="Weight" class="small text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Repetitions"></label>
                        <input asp-for="Repetitions" class="form-control" placeholder="enter repetitions here...">
                        <span asp-validation-for="Repetitions" class="small text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Sets"></label>
                        <input asp-for="Sets" class="form-control" placeholder="enter sets here...">
                        <span asp-validation-for="Sets" class="small text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="WeekDay"></label>
                        <select asp-for="WeekDay" class="form-control">
                            @foreach (int weekday in Enum.GetValues(typeof(WeekDay)))
                            {
                                <option value="@weekday">@Enum.GetName(typeof(WeekDay), weekday)</option>
                            }
                        </select>
                    </div>
                <div class="text-center pt-3">
                    <input class="btn btn-outline-secondary" type="submit" value="Add to exercise diary" />
                </div>

            </form>
        </div>
    </div>
</div>