MyFitnessApp/Web/MyFitnessApp.Web/Controllers/BlogsController.cs
namespace MyFitnessApp.Web.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyFitnessApp.Services.Data.Article;
    using MyFitnessApp.Web.Filters;
    using MyFitnessApp.Web.ViewModels.Articles;

    [Authorize]
    [TypeFilter(typeof(RestrictBannedUsersAttribute))]
    [TypeFilter(typeof(RestrictUsersWithoutProfileAttribute))]
    public class BlogsController : Controller
    {
        private readonly IArticlesService articlesService;

        public BlogsController(IArticlesService articlesService)
        {
            this.articlesService = articlesService;
        }

        [HttpGet]
        public IActionResult Recipes()
        {
            var view = new AllArticlesViewModel
            {
                Articles = this.articlesService.GetArticlesByCategoryId(1),
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Fitness()
        {
            var view = new AllArticlesViewModel
            {
                Articles = this.articlesService.GetArticlesByCategoryId(2),
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Nutrition()
        {
            var view = new AllArticlesViewModel
            {
                Articles = this.articlesService.GetArticlesByCategoryId(3),
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Weightloss()
        {
            var view = new AllArticlesViewModel
            {
                Articles = this.articlesService.GetArticlesByCategoryId(4),
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Inspiration()
        {
            var view = new AllArticlesViewModel
            {
                Articles = this.articlesService.GetArticlesByCategoryId(5),
            };

            return this.View(view);
        }

        [HttpGet]
        public IActionResult Essentials()
        {
            var view = new AllArticlesViewModel
            {
                Articles = this.articlesService.GetArticlesByCategoryId(6),
            };

            return this.View(view);
        }
    }
}

MyFitnessApp/Web/MyFitnessApp.Web/Controllers/SearchController.cs
namespace MyFitnessApp.Web.Controllers
{
    using System.Linq;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using MyFitnessApp.Services.Data.Search;
    using MyFitnessApp.Web.Filters;
    using MyFitnessApp.Web.ViewModels.Search;

    [Authorize]
    [TypeFilter(typeof(RestrictBannedUsersAttribute))]
    [TypeFilter(typeof(RestrictUsersWithoutProfileAttribute))]
    public class SearchController : Controller
    {
        private readonly ISearchService searchService;

        public SearchController(ISearchService searchService)
        {
            this.searchService = searchService;
        }

        [HttpGet]
        public IActionResult SearchFood()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult SearchFood(FoodInputModel model)
        {
            var foods = this.searchService.SearchFoodByKeyword(model.Keyword);
            if (foods.Any())
            {
                var viewModel = new AllFoodsViewModel
                {
                    Foods = foods,
                };
                return this.View("FoundFood", viewModel);
            }
            else
            {
                this.TempData["Message"] = "There was no food found with the given keyword.";
                return this.View();
            }
        }

        [HttpGet]
        public IActionResult SearchArticle()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult SearchArticle(ArticleInputModel model)
        {
            var articles = this.searchService.SearchArticleByKeyword(model.Keyword);
            if (articles.Any())
            {
                var viewModel = new AllArticlesViewModel
                {
                    Articles = articles,
                };
                return this.View("FoundArticle", viewModel);
            }
            else
            {
                this.TempData["Message"] = "There was no article title found with the given keyword.";
                return this.View();
            }
        }

        [HttpGet]
        public IActionResult SearchExercise()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult SearchExercise(ExerciseInputModel model)
        {
            var exercises = this.searchService.SearchExerciseByKeyword(model.Keyword);
            if (exercises.Any())
            {
                var viewModel = new AllExercisesViewModel
                {
                    Exercises = exercises,
                };
                return this.View("FoundExercise", viewModel);
            }
            else
            {
                this.TempData["Message"] = "There was no exercise found with the given keyword.";
                return this.View();
            }
        }

        [HttpGet]
        public IActionResult SearchUser()
        {
            return this.View();
        }

        [HttpPost]
        public IActionResult SearchUser(UserInputModel model)
        {
            if (model.UserName != null)
            {
                var username = model.UserName;
                var users = this.searchService.SearchUserByUsername(username);

                if (users.Any())
                {
                    var viewModel = new AllUsersViewModel()
                    {
                        Users = users,
                    };
                    return this.View("FoundUser", viewModel);
                }
                else
                {
                    this.TempData["Message"] = "There was no user found with the given username.";
                    return this.View();
                }
            }
            else if (model.Email != null)
            {
                if (model.Email != null)
                {
                    var email = model.Email;
                    var users = this.searchService.SearchUserByEmail(email);

                    if (users.Any())
                    {
                        var viewModel = new AllUsersViewModel()
                        {
                            Users = users,
                        };
                        return this.View("FoundUser", viewModel);
                    }
                    else
                    {
                        this.TempData["Message"] = "There was no user found with the given email.";
                        return this.View();
                    }
                }
            }

            return this.View();
        }
    }
}

MyFitnessApp/Web/MyFitnessApp.Web/Views/Search/FoundArticle.cshtml
@model MyFitnessApp.Web.ViewModels.Search.AllArticlesViewModel

@{
    this.ViewData["Title"] = "Found articles";
}

<!-- Breadcrumb -->
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Articles/All">All articles</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@this.ViewData["Title"]</strong></li>
    </ol>
</nav>
<!-- /Breadcrumb -->


<div>
    <div class="row">
        @foreach (var article in Model.Articles.OrderBy(x => x.Title))
        {
            <div class="text-center col-lg-4 col-xl-4 col-md-4 col-sm-12 col-12 mt-3" style="width: 18rem;">
                <div class='card border-dark'>
                    <div class="card-header col-md border text-center">
                        <a asp-controller="Articles" asp-action="Article" asp-route-id="@article.Id">
                            <img src="@article.ImagePath" class="card-img-top">
                        </a>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title"> <a asp-controller="Articles" asp-action="Article" asp-route-id="@article.Id">@article.Title</a></h5>
                        <p class="card-text text-justify">@article.ShortContent</p>
                    </div>
                    <div class="card-footer">
                        Article category:
                        <a asp-controller="Blogs" asp-action="@article.CategoryName">
                            <p class="card-text"> @article.CategoryName</p>
                        </a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<hr />

<div class="text-center">
    <a asp-controller="Search" asp-action="SearchArticle" class="btn btn-outline-secondary m-2">Search again</a>
</div>

MyFitnessApp/Web/MyFitnessApp.Web/Views/Search/FoundExercise.cshtml
@model MyFitnessApp.Web.ViewModels.Search.AllExercisesViewModel

@{
    this.ViewData["Title"] = "Found exercises";
}


<!-- Breadcrumb -->
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Exercises/All">All exercises</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@this.ViewData["Title"]</strong></li>
    </ol>
</nav>
<!-- /Breadcrumb -->


<div class="row">
    @foreach (var exercise in this.Model.Exercises.OrderBy(x => x.Name))
    {
        <div class="col-xl-4 col-lg-6 col-md-6 col-sm-12 col-12 p-1">
            <a asp-controller="Exercises" asp-action="Add" asp-route-id="@exercise.Id">
                <div class="card border-dark">
                    <div class="card card-body text-center alert-secondary">
                        <div class="text">
                            <h6><strong> @exercise.Name</strong></h6>
                        </div>
                        <div class="media flex-wrap w-100 align-items-center mt-2">
                            <img src="@exercise.ImageUrl" width="220" class="card-img-top">
                        </div>
                        <div class="text-muted mt-2">
                            Category: @exercise.CategoryName
                        </div>
                        <div class="text-muted">
                            Difficulty: @exercise.DifficultyName
                        </div>
                        <div class="text-muted">
                            Equipment: @exercise.EquipmentName
                        </div>
                    </div>
                </div>
            </a>
        </div>
    }
</div>

<hr />

<div class="text-center">
    <a asp-controller="Search" asp-action="SearchExercise" class="btn btn-outline-secondary m-2">Search again</a>
</div>

MyFitnessApp/Web/MyFitnessApp.Web/Views/Search/FoundFood.cshtml
@model MyFitnessApp.Web.ViewModels.Search.AllFoodsViewModel

@{
    this.ViewData["Title"] = "Found foods";
}

<!-- Breadcrumb -->
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Foods/All">All foods</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@this.ViewData["Title"]</strong></li>
    </ol>
</nav>
<!-- /Breadcrumb -->

<div class="col-md-8 offset-2">
    <ol class="list-group list-group-numbered">
        @foreach (var food in Model.Foods.OrderBy(x => x.Name))
        {
            <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="container">
                    <div class="row">
                        <div class="col-md-4 align-self-center">
                            <div>
                                <h6><strong>@food.Name</strong></h6>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div><strong>Protein:</strong> @food.ProteinIn100Grams gr.</div>
                            <div><strong>Carbohydrates:</strong> @food.CarbohydratesIn100Grams gr.</div>
                            <div><strong>Fats:</strong> @food.FatIn100Grams gr.</div>
                            <div><strong>Total calories:</strong> @food.TotalCalories</div>
                        </div>

                        <div class="col-md-4 align-self-center text-center">
                            <a asp-controller="Foods" asp-action="Add" asp-route-id="@food.Name" class="btn btn-outline-secondary m-4">Select food</a>
                        </div>
                    </div>
                </div>
            </li>
        }
    </ol>
</div>

<hr />

<div class="text-center">
    <a asp-controller="Search" asp-action="SearchFood" class="btn btn-outline-secondary m-2">Search again</a>
</div>

MyFitnessApp/Web/MyFitnessApp.Web/Views/Search/FoundUser.cshtml
@model MyFitnessApp.Web.ViewModels.Search.AllUsersViewModel

@{
    this.ViewData["Title"] = $"Found users";
}

<!-- Breadcrumb -->
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Users/All">All  users</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@this.ViewData["Title"]</strong></li>
    </ol>
</nav>
<!-- /Breadcrumb -->

<div class="row">
    @foreach (var user in this.Model.Users)
    {
        <div class="col-lg-3 offset-lg-0 col-xl-3 offset-xl-0 col-md-4 offset-md-0 col-sm-6 offset-sm-3 col-8 offset-2 text-center pt-2">
            <a asp-controller="Profiles" asp-action="UsersProfile" asp-route-username="@user.UserName">
                <div class="card-header border border-dark text-center">
                    <div class="media flex-wrap w-auto align-items-center">
                        <div class="col">
                            <div class="media-body text-center">
                                <div class="text-dark">
                                    <h4>@user.UserName</h4>
                                </div>
                                <div class="text-center rounded mx-auto d-block">
                                    <img src="@user.UserProfileImage" class="rounded-circle" width="150">
                                </div>
                                <div class="text-muted">
                                    @user.FirstName @user.LastName
                                </div>
                                <div class="text-muted">
                                    @user.Email
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    }
</div>

<hr />

<div class="text-center">
    <a asp-controller="Search" asp-action="SearchUser" class="btn btn-outline-secondary m-2">Search again</a>
</div>

MyFitnessApp/Web/MyFitnessApp.Web/Views/Search/SearchArticle.cshtml
@model MyFitnessApp.Web.ViewModels.Search.ArticleInputModel

@{
    this.ViewData["Title"] = "Search for an article";
}

<!-- Breadcrumb -->
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Articles/All">All articles</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@this.ViewData["Title"]</strong></li>
    </ol>
</nav>
<!-- /Breadcrumb -->

@if (this.TempData.ContainsKey("Message"))
{
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <strong>@this.TempData["Message"]</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="container">
    <div class="row">
        <div class="offset-lg-2 col-lg-8 col-sm-12 offset-xl-3 col-xl-6">
            <form method="post">
                <div class="form-group">
                    <label asp-for="Keyword">Search for an article title using a keyword</label>
                    <input asp-for="Keyword" class="form-control" placeholder="Enter a word" />
                </div>
                <div class="text-center pt-2">
                    <input class="btn btn-outline-secondary" type="submit" value="Search" />
                </div>
            </form>
        </div>
    </div>
</div>

MyFitnessApp/Web/MyFitnessApp.Web/Views/Search/SearchExercise.cshtml
@model MyFitnessApp.Web.ViewModels.Search.ExerciseInputModel

@{
    this.ViewData["Title"] = "Search for an exercise";
}

<!-- Breadcrumb -->
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Exercises/All">All exercises</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@this.ViewData["Title"]</strong></li>
    </ol>
</nav>
<!-- /Breadcrumb -->

@if (this.TempData.ContainsKey("Message"))
{
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <strong>@this.TempData["Message"]</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="container">
    <div class="row">
        <div class="offset-lg-2 col-lg-8 col-sm-12 offset-xl-3 col-xl-6">
            <form method="post">
                <div class="form-group">
                    <label asp-for="Keyword">Search for an exercise by name or category using a keyword</label>
                    <input asp-for="Keyword" class="form-control" placeholder="Enter a word" />
                </div>
                <div class="text-center pt-2">
                    <input class="btn btn-outline-secondary" type="submit" value="Search" />
                </div>
            </form>
        </div>
    </div>
</div>

MyFitnessApp/Web/MyFitnessApp.Web/Views/Search/SearchFood.cshtml
@model MyFitnessApp.Web.ViewModels.Search.FoodInputModel

@{
    this.ViewData["Title"] = "Search for food";
}

<!-- Breadcrumb -->
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Foods/All">All foods</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@this.ViewData["Title"]</strong></li>
    </ol>
</nav>
<!-- /Breadcrumb -->

@if (this.TempData.ContainsKey("Message"))
{
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <strong>@this.TempData["Message"]</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="container">
    <div class="row">
        <div class="offset-lg-2 col-lg-8 col-sm-12 offset-xl-3 col-xl-6">
            <form method="post">
                <div class="form-group">
                    <label asp-for="Keyword">Search for a food name using a keyword</label>
                    <input asp-for="Keyword" class="form-control" placeholder="Enter a word" />
                </div>
                <div class="text-center pt-2">
                    <input class="btn btn-outline-secondary" type="submit" value="Search" />
                </div>
            </form>
        </div>
    </div>
</div>

MyFitnessApp/Web/MyFitnessApp.Web/Views/Search/SearchUser.cshtml
@model MyFitnessApp.Web.ViewModels.Search.UserInputModel

@{
    this.ViewData["Title"] = "Search for a user";
}

<!-- Breadcrumb -->
<nav aria-label="breadcrumb" class="main-breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="/Users/All">All  users</a></li>
        <li class="breadcrumb-item active" aria-current="page"><strong>@this.ViewData["Title"]</strong></li>
    </ol>
</nav>
<!-- /Breadcrumb -->

@if (this.TempData.ContainsKey("Message"))
{
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
        <strong>@this.TempData["Message"]</strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="container">
    <div class="row">
        <div class="offset-lg-2 col-lg-8 col-sm-12 offset-xl-3 col-xl-6">
            <form method="post">
                <div class="form-group">
                    <label asp-for="UserName">Search for a user using username</label>
                    <input asp-for="UserName" class="form-control" placeholder="Enter user's username" />
                </div>
                <div class="form-group">
                    <label asp-for="Email">Search for a user using E-mail</label>
                    <input asp-for="Email" class="form-control" placeholder="Enter user's E-mail" />
                </div>
                <div class="text-center pt-2">
                    <input class="btn btn-outline-secondary" type="submit" value="Search" />
                </div>
            </form>
        </div>
    </div>
</div>